<a href="https://colab.research.google.com/github/Ahmedsssy/ahmed-ai/blob/main/Python_Numpy_Exercises_with_hints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python NumPy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` and print the numpy version and the configuration (★☆☆)

`Hint: import … as` and `np.__version__, np.show_config)`

In [2]:
import numpy as np



print("NumPy Version:", np.__version__)


np.show_config()


NumPy Version: 2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: 

#### 2. Convert a list of numeric value into a one-dimensional NumPy array (★☆☆)
`💡 hint: numpy.array`

In [4]:
import numpy as np

# List of numeric values
my_list = [1, 2, 3, 4, 5]

arr=np.array(my_list)

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### 3. Create a null vector of size 9 (★☆☆)
`💡 hint: np.zeros`

In [5]:
null_vector = np.zeros(9)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)
`💡 hint: size, itemsize`

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# مصفوفة مثال
arr = np.array([1, 2, 3, 4, 5])

# حساب حجم الذاكرة
memory_size = arr.size * arr.itemsize

print("Memory size in bytes:", memory_size)


Memory size in bytes: 40


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`💡hint: np.info`

In [14]:
import numpy as np

help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 12

*   List item
*   List item

but the sixth value which is 1 (★☆☆)
`💡hint: array[12]`

In [ ]:
import numpy as np

null_vector = np.zeros(12)

null_vector[5] = 1

print(null_vector)

#### 7. Create a vector with values ranging from 20 to 59 (★☆☆)
`💡hint: arange`

In [ ]:
import numpy as np

vector = np.arange(20, 60)

print(vector)

#### 8. Reverse a vector (first element becomes last) (★☆☆)
`💡hint: array[::-1]`

In [ ]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])

reversed_vector = vector[::-1]

print(reversed_vector)

#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`

In [ ]:
import numpy as np

matrix = np.arange(12, 21).reshape(3, 3)

print(matrix)

#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`

In [ ]:
import numpy as np

arr = np.array([3, 7, 0, 0, 9, 0])

non_zero_indices = np.nonzero(arr)

print(non_zero_indices)

#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [ ]:
import numpy as np

identity_matrix = np.eye(4)

print(identity_matrix)

#### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [ ]:
import numpy as np

arr = np.random.rand(9, 9)

min_value = np.min(arr)
max_value = np.max(arr)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [ ]:
import numpy as np

vector = np.random.rand(20)

mean_value = np.mean(vector)

print("Mean value:", mean_value)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [ ]:
import numpy as np

arr = np.ones((5, 5))

arr[1:-1, 1:-1] = 0

print(arr)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

In [ ]:
import numpy as np

#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`

In [ ]:
import numpy as np

matrix = np.zeros((6, 6))

values = [1, 2, 3, 4]

matrix = np.diag(values, k=-1)

print(matrix)

#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [ ]:
import numpy as np

matrix = np.zeros((6, 6), dtype=int)

matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1

print(matrix)

#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [ ]:
import numpy as np

shape = (8, 9, 10)
index = 100

result = np.unravel_index(index, shape)

print(result)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`💡hint: np.tile`

In [ ]:
import numpy as np

pattern = np.array([[0, 1], [1, 0]])

checkerboard = np.tile(pattern, (4, 4))

print(checkerboard)

#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`

In [ ]:
import numpy as np

matrix = np.random.rand(6, 6)

mean = np.mean(matrix)
std = np.std(matrix)

normalized_matrix = (matrix - mean) / std

#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

num_elements = arr.size
element_size = arr.itemsize
total_bytes = arr.nbytes

#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [ ]:
import numpy as np

matrix1 = np.random.rand(6, 3)
matrix2 = np.random.rand(3, 4)

result = np.dot(matrix1, matrix2)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[(arr > 3) & (arr < 8)] *= -1

#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
import numpy as np
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
import numpy as np

a = np.array([1, 2])
b = np.array([4, 5])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

In [ ]:
import numpy as np

a = np.array([1, 2, 3])

#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [ ]:
import numpy as np

arr = np.array([-1.2, 0.5, -3.7, 2.4])

rounded_arr = np.where(arr >= 0, np.ceil(arr), np.floor(arr))

#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`💡hint: np.seterr, np.errstate`

In [ ]:
import numpy as np

np.seterr(all='ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`💡hint: imaginary number`

In [ ]:
import numpy as np

print(np.sqrt(-1) == np.emath.sqrt(-1))

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`💡hint: np.datetime64, np.timedelta64`

In [ ]:
import numpy as np

yesterday = np.datetime64('today') - np.timedelta64(1, 'D')
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of January 2016? (★★☆)
`💡hint: np.arange(dtype=datetime64['D'])`

In [ ]:
import numpy as np

dates = np.arange('2016-01', '2016-02', dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

In [ ]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`💡hint: %, np.floor, astype, np.trunc`

In [ ]:
import numpy as np

arr = np.random.rand(5) * 10

#### 37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)
`💡hint: np.arange`

In [ ]:
import numpy as np

matrix = np.zeros((3, 3))
matrix += np.arange(3)

#### 38. Consider a generator function that generates 9 integers and use it to build an array (★☆☆)
`💡hint: np.fromiter`

In [ ]:
import numpy as np

def generate_integers():
    for i in range(9):
        yield i

arr = np.fromiter(generate_integers(), dtype=int)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`💡hint: np.linspace`

In [ ]:
import numpy as np

vector = np.linspace(0, 1, num=10, endpoint=False)[1:]

#### 40. Create a random vector of size 10 and sort it (★★☆)
`💡hint: sort`

In [15]:
import numpy as np

vector = np.random.rand(10)
vector.sort()

#### 41. How to sum a small array faster than np.sum? (★★☆)
`💡hint: np.add.reduce`

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = np.add.reduce(arr)

#### 42. Consider two random array A and B, check if they are equal (★★☆)
`💡hint: np.allclose, np.array_equal`

In [ ]:
import numpy as np

A = np.random.rand(5)
B = np.random.rand(5)

are_equal = np.allclose(A, B)

#### 43. Make an array immutable (read-only) (★★☆)
`💡hint: flags.writeable`

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr.flags.writeable = False

#### 44. Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`💡hint: np.sqrt, np.arctan2`

In [17]:
from re import X
import numpy as np

cartesian_coordinates = np.random.rand(5, 2)

x = cartesian_coordinates[:, 0]
y = cartesian_coordinates[:, 1]
print (X)
print(y)

re.VERBOSE
[0.76189976 0.81976904 0.42708826 0.59234129 0.30627657]


#### 45. Create random vector of size 5 and replace the maximum value by 0 (★★☆)
`💡hint: argmax`

In [ ]:
import numpy as np

vector = np.random.rand(5)
max_index = np.argmax(vector)
vector[max_index] = 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`💡hint: np.meshgrid`

In [ ]:
import numpy as np

x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)

X, Y = np.meshgrid(x, y)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`💡hint: np.subtract.outer`

In [ ]:
import numpy as np

X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

C = 1 / (X[:, np.newaxis] - Y)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`💡hint: np.iinfo, np.finfo, eps`

In [ ]:
import numpy as np

#### 49. How to print all the values of an array? (★★☆)
`💡hint: np.set_printoptions`

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

np.set_printoptions(threshold=np.inf)
print(arr)

[1 2 3 4 5]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`💡hint: argmin`

In [ ]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])
scalar = 3.5

closest_value = vector[np.argmin(np.abs(vector - scalar))]

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`💡hint: dtype`

In [ ]:
import numpy as np

# تعريف نوع البيانات (structure)
dt = np.dtype([
    ('position', [('x', 'f4'), ('y', 'f4')]),  # f4 = float32
    ('color', [('r', 'u1'), ('g', 'u1'), ('b', 'u1')])  # u1 = unsigned int8
])

# إنشاء structured array مع مثال بيانات
data = np.array([
    ((0.0, 0.0), (255, 0, 0)),   # أحمر
    ((1.0, 1.0), (0, 255, 0)),   # أخضر
    ((2.0, 2.0), (0, 0, 255))    # أزرق
], dtype=dt)

print(data)
print("X positions:", data['position']['x'])
print("Red values:", data['color']['r'])


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`💡hint: np.atleast_2d, T, np.sqrt`

In [ ]:
import numpy as np

coordinates = np.random.rand(100, 2)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
`💡hint: view and [:] =`

In [ ]:
import numpy as np

float_array = np.array([1.0, 2.5, 3.7, 4.2], dtype=np.float32)

int_array = float_array.view(np.int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint: np.genfromtxt`

In [ ]:
import numpy as np

file_content = """1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11"""

lines = file_content.split('\n')

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`💡hint: np.ndenumerate, np.ndindex`

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#### 56. Generate a generic 2D Gaussian-like array (★★☆)
`💡hint: np.meshgrid, np.exp`

In [ ]:
import numpy as np

x, y = np.meshgrid(np.linspace(-1, 1, 5), np.linspace(-1, 1, 5))

#### 57. How to randomly place e elements in a 2D array? (★★☆)
`💡hint: np.put, np.random.choice`

In [ ]:
import numpy as np

n = 10
p = 3

arr = np.zeros((n, n))
np.put(arr, np.random.choice(range(n*n), p, replace=False), 1)

#### 58. Subtract the mean of each row of a matrix (★★☆)
`💡hint: mean(axis=,keepdims=)`

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#### 59. How to sort an array by the nth column? (★★☆)
`💡hint: argsort`

In [ ]:
import numpy as np

arr = np.array([[3, 1, 2], [6, 4, 5], [9, 7, 8]])
n = 1

#### 60. How to tell if a given 2D array has null columns? (★★☆)
`💡hint: any, ~`

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#### 61. Find the nearest value from a given value in an array (★★☆)
`💡hint: np.abs, argmin, flat`

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
given_value = 3.5

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`💡

In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4], [5], [6]])

#### 63. Create an array class that has a name attribute (★★☆)
`💡hint: class method`

In [ ]:
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`💡hint: np.bincount | np.add.at`

In [ ]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 2, 4])

np.add.at(vector, indices, 1)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`💡hint: np.bincount`

In [ ]:
import numpy as np

X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 2, 2, 4])

F = np.bincount(I, weights=X)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`💡hint: np.unique`

In [ ]:
import numpy as np

image = np.random.randint(0, 256, size=(10, 10, 3), dtype=np.uint8)

unique_colors = np.unique(image.reshape(-1, 3), axis=0)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`💡hint: sum(axis=(-2,-1))`

In [ ]:
import numpy as np

arr = np.random.rand(2, 3, 4, 5)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`💡hint: np.bincount`

In [ ]:
import numpy as np

# بيانات المثال
D = np.array([10, 20, 30, 40, 50, 60])
S = np.array([0, 0, 1, 1, 2, 2])  # مؤشرات المجموعات

# حساب مجموع كل subset
sum_per_subset = np.bincount(S, weights=D)

# حساب عدد العناصر في كل subset
count_per_subset = np.bincount(S)

# حساب المتوسط لكل subset
mean_per_subset = sum_per_subset / count_per_subset

print("Mean per subset:", mean_per_subset)


#### 69. How to get the diagonal of a dot product? (★★★)
`💡hint: np.diag`

In [ ]:
import numpy as np

# مصفوفتين عشوائيتين كمثال
A = np.random.randint(0, 10, (4, 4))
B = np.random.randint(0, 10, (4, 4))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# حساب dot product
dot_product = np.dot(A, B)

# استخراج القطر
diagonal = np.diag(dot_product)

print("Dot Product:\n", dot_product)
print("Diagonal of Dot Product:", diagonal)


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`💡hint: array[::4]`

In [20]:
import numpy as np

# المتجه الأصلي
vec = np.array([1, 2, 3, 4, 5])

# حجم المتجه الجديد = عدد العناصر × (عدد الأصفار + 1)
new_vec = np.zeros(len(vec) * 4 - 3, dtype=int)

# وضع القيم الأصلية كل 4 خطوات
new_vec[::4] = vec

print(new_vec)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
`💡hint: array[:, :, None]`

In [21]:
import numpy as np

# مصفوفة (5,5,3)
A = np.ones((5, 5, 3))

# مصفوفة (5,5)
B = np.arange(25).reshape(5, 5)

# إعادة تشكيل B إلى (5,5,1) عشان البث (broadcasting)
B_reshaped = B[:, :, np.newaxis]

# الضرب مع البث
C = A * B_reshaped

print(C.shape)  # (5,5,3)
print(C)


(5, 5, 3)
[[[ 0.  0.  0.]
  [ 1.  1.  1.]
  [ 2.  2.  2.]
  [ 3.  3.  3.]
  [ 4.  4.  4.]]

 [[ 5.  5.  5.]
  [ 6.  6.  6.]
  [ 7.  7.  7.]
  [ 8.  8.  8.]
  [ 9.  9.  9.]]

 [[10. 10. 10.]
  [11. 11. 11.]
  [12. 12. 12.]
  [13. 13. 13.]
  [14. 14. 14.]]

 [[15. 15. 15.]
  [16. 16. 16.]
  [17. 17. 17.]
  [18. 18. 18.]
  [19. 19. 19.]]

 [[20. 20. 20.]
  [21. 21. 21.]
  [22. 22. 22.]
  [23. 23. 23.]
  [24. 24. 24.]]]


#### 72. How to swap two rows of an array? (★★★)
`💡hint: array[[]] = array[[]]`

In [ ]:
import numpy as np

# مصفوفة (3,3)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`💡hint: repeat, np.roll, np.sort, view, np.unique`

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`💡hint: np.repeat`

In [22]:
import numpy as np

# مثال على C (ناتجة من bincount)
C = np.array([0, 2, 3, 1])


A = np.repeat(np.arange(len(C)), C)

print("C:", C)
print("A:", A)
print("Check:", np.bincount(A))


C: [0 2 3 1]
A: [1 1 2 2 2 3]
Check: [0 2 3 1]


#### 75. How to compute averages using a sliding window over an array? (★★★)
`💡hint: np.cumsum`

In [ ]:
import numpy as np

# بيانات المثال
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`💡hint: from numpy.lib import stride_tricks`

In [ ]:
import numpy as np

Z = np.arange(10)

# بناء المصفوفة
result = np.array([Z[i:i+3] for i in range(len(Z)-2)])

print(result)


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`💡hint: np.logical_not, np.negative`

In [ ]:
import numpy as np

# بيانات المثال
arr = np.array([True, False, True, False])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [23]:
import numpy as np

# مثال بيانات
P0 = np.random.rand(5, 2)  # 5 خطوط - نقاط البداية
P1 = np.random.rand(5, 2)  # 5 خطوط - نقاط النهاية
P  = np.random.rand(10, 2) # 10 نقاط

# المتجهات من بداية الخط إلى نهايته
line_vec = P1 - P0  # (5, 2)

# المتجهات من بداية الخط إلى النقاط
point_vec = P[None, :, :] - P0[:, None, :]  # (5, 10, 2)

# حساب cross product في 2D: (x1*y2 - y1*x2)
cross_prod = line_vec[:, None, 0] * point_vec[:, :, 1] - \
             line_vec[:, None, 1] * point_vec[:, :, 0]

# المسافات = القيمة المطلقة لـ cross / طول الخط
distances = np.abs(cross_prod) / np.linalg.norm(line_vec, axis=1)[:, None]

print(distances.shape)  # (5 خطوط × 10 نقاط)
print(distances)


(5, 10)
[[0.18444669 0.13992108 0.02782525 0.76207568 0.07360416 0.30988391
  0.56319475 0.01483853 0.61368877 0.64360331]
 [0.07321784 0.15755888 0.62683729 0.10524042 0.70552775 0.66354306
  0.14616845 0.67491593 0.03699543 0.40844137]
 [0.5632021  0.50990819 0.15255791 0.09095502 0.10605534 0.14212194
  0.19987104 0.09300686 0.35073651 0.13225685]
 [0.78774665 0.77319948 0.60841711 0.1591185  0.59928448 0.22783921
  0.3378522  0.55991211 0.41786715 0.0632289 ]
 [0.08336888 0.12301714 0.2614205  0.51250022 0.30276559 0.08825439
  0.31109958 0.24459581 0.34972786 0.41270819]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`💡hint: minimum maximum`

In [ ]:
import numpy as np

def extract_subarray(arr, center, shape, fill_value=0):
    """
    Extract subarray of given shape centered at `center` from `arr`.
    Pads with fill_value if needed.

    Parameters:
        arr (ndarray): المصفوفة الأصلية
        center (tuple): إحداثيات المركز (مثلاً (y, x))
        shape (tuple): حجم الجزء المطلوب (مثلاً (3, 3))
        fill_value: قيمة التعبئة

    Returns:
        ndarray: الجزء المطلوب
    """
    arr = np.asarray(arr)
    ndim = arr.ndim
    half_shape = [(s // 2) for s in shape]

    # حجم الـ padding
    pad_width = [(h, s - h - 1) for h, s in zip(half_shape, shape)]
    arr_padded = np.pad(arr,
                        [(pw[0], pw[1]) for pw in pad_width],
                        mode='constant',
                        constant_values=fill_value)

    # تعديل إحداثيات المركز مع الـ padding
    adj_center = tuple(c + pw[0] for c, pw in zip(center, pad_width))

    slices = tuple(slice(ac - hs, ac + hs + 1)
                   for ac, hs in zip(adj_center, half_shape))

    return arr_padded[slices]

# مثال
arr = np.arange(25).reshape(5, 5)
center = (0, 0)
shape = (3, 3)
sub = extract_subarray(arr, center, shape, fill_value=-1)

print(arr)
print(sub)


#### 81. Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`💡hint: stride_tricks.as_strided`

In [ ]:
import numpy as np

# بيانات المثال
arr = np.arange(1, 15)

#### 82. Compute a matrix rank (★★★)
`💡hint: np.linalg.svd`

In [ ]:
import numpy as np

# بيانات المثال
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# حساب rank
rank = np.linalg.matrix_rank(arr)

#### 83. How to find the most frequent value in an array?
`💡hint: np.bincount, argmax`

In [ ]:
import numpy as np

# بيانات المثال
arr = np.array([1, 2, 3, 2, 4, 2, 5, 2, 6])

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`💡hint: stride_tricks.as_strided`

In [ ]:
import numpy as np

# بيانات المثال
arr = np.random.randint(0, 10, (10, 10))

#### 85. Create a 2D array subclass such that a[i,j] == a[j,i] (★★★)
`💡hint: class method`

In [ ]:
import numpy as np

class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`💡hint: np.tensordot`

In [ ]:
import numpy as np

# مثال بيانات
p = 3
n = 4
matrices = np.random.rand(p, n, n)
vectors = np.random.rand(p, n, 1)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`💡hint: np.add.reduceat`

In [ ]:
import numpy as np

# بيانات المثال
arr = np.random.randint(0, 10, (16, 16))

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
import numpy as np

# مثال بيانات
arr = np.random.randint(0, 2, (10, 10))

#### 89. How to get the n largest values of an array (★★★)
`💡hint: np.argsort | np.argpartition`

In [ ]:
import numpy as np

# بيانات المثال
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`💡hint: np.indices`

In [ ]:
import numpy as np

# مثال بيانات
vectors = [np.array([1, 2, 3]), np.array([4, 5]), np.array([6, 7])]

#### 91. How to create a record array from a regular array? (★★★)
`💡hint: np.core.records.fromarrays`

In [ ]:
import numpy as np

# بيانات المثال
arr = np.array([(1, 'Alice', 25), (2, 'Bob', 30), (3, 'Charlie', 35)])

#### 92. Consider a large vector A, compute A to the power of 3 using 3 different methods (★★★)
`💡hint: np.power, *, np.einsum`

In [ ]:
import numpy as np

# بيانات المثال
arr = np.random.rand(1000000)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`💡hint: np.where`

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
import numpy as np

# بيانات المثال
arr = np.array([[1, 2, 3], [2, 2, 3], [4, 5, 6], [2, 2, 3], [7, 8, 9]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
`💡hint: np.unpackbits`

In [ ]:
import numpy as np

# بيانات المثال
arr = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
`💡hint: np.ascontiguousarray | np.unique`

In [ ]:
import numpy as np

# بيانات المثال
arr = np.array([[1, 2, 3], [2, 2, 3], [4, 5, 6], [2, 2, 3], [7, 8, 9]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`💡hint: np.einsum`

In [ ]:
import numpy as np

# بيانات المثال
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`💡hint: np.cumsum, np.interp`

In [ ]:
import numpy as np

# بيانات المثال
X = np.array([0, 1, 2, 3, 4])
Y = np.array([0, 1, 0, 1, 0])

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`💡hint: np.logical_and.reduce, np.mod`

In [ ]:
import numpy as np

# مثال بيانات
n = 10
X = np.array([[3, 7], [4, 6], [1, 9], [2, 8]])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`💡hint: np.percentile`

In [24]:
import numpy as np

def bootstrap_ci_mean(X, N=1000, ci=95):
    """
    Bootstrap confidence interval for the mean of X.

    Parameters:
        X (array-like): البيانات الأصلية
        N (int): عدد العينات bootstrap
        ci (float): نسبة الثقة (مثلاً 95)

    Returns:
        (low, high): حدود فترة الثقة
    """
    X = np.asarray(X)
    means = np.empty(N)
    n = len(X)

    for i in range(N):
        sample = np.random.choice(X, size=n, replace=True)
        means[i] = sample.mean()

    alpha = (100 - ci) / 2
    lower = np.percentile(means, alpha)
    upper = np.percentile(means, 100 - alpha)
    return lower, upper

# مثال
X = np.random.randn(100)  # بيانات عشوائية
low, high = bootstrap_ci_mean(X, N=10000)
print(f"95% CI: [{low:.3f}, {high:.3f}]")


95% CI: [-0.334, 0.044]
